import { Request, Response } from "express";
import * as phoneService from "../services/phoneService";

/**
 * Fetches all available phones from the database.
 * @route GET /api/phones
 * @param req The Express request object
 * @param res The Express response object
 * @returns The list of phones
 */
export const getAllPhones = async (req: Request, res: Response) => {
  try {
    const phones = await phoneService.findAllPhones();
    res.status(200).json(phones);
  } catch (err) {
    console.error("Error fetching phones:", err);
    res.status(500).json({ message: "Server error fetching phones" });
  }
};

/**
 * Fetches a specific phone using its ID,
 * @route GET /api/phones/:id
 * @param req The Express request object containing the 'id' param
 * @param res The Express response object
 * @returns The phone data
 */
export const getPhoneById = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const phone = await phoneService.findPhoneById(id);
    if (!phone) {
      return res.status(404).json({ message: `Phone with ID '${id}' not found` });
    }
    res.status(200).json(phone);
  } catch (err) {
    console.error(`Error fetching phone ${req.params.id}:`, err);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * Creates a new phone. The 'id' field is auto-generated by the model if omitted.
 * @route POST /api/phones
 * @param req The Express request object containing phone data in the body
 * @param res The Express response object
 * @returns The created phone object
 */
export const createPhone = async (req: Request, res: Response) => {
  try {
    // Validation the schema just incase there are missing fields
    if (!req.body.name || !req.body.brand) {
      return res.status(400).json({ message: "Missing required fields: name, brand" });
    }

    const newPhone = await phoneService.createNewPhone(req.body);
    res.status(201).json(newPhone);
  } catch (err: any) {
    console.error("Error creating phone:", err);

    // Handling duplicate key error
    if (err.code === 11000) {
      return res.status(409).json({ message: "A phone with this ID already exists." });
    }
    res.status(500).json({ message: "Server error creating phone" });
  }
};

/**
 * Updates an existing phone's details.
 * @route PUT /api/phones/:id
 * @param req - The Express request object containing 'id' param and update data
 * @param res - The Express response object
 * @returns The updated phone object
 */
export const updatePhone = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const updatedPhone = await phoneService.updatePhoneById(id, req.body);

    if (!updatedPhone) {
      return res.status(404).json({ message: "Phone not found for update" });
    }

    res.status(200).json(updatedPhone);
  } catch (err) {
    console.error("Error updating phone:", err);
    res.status(500).json({ message: "Server error updating phone" });
  }
};

/**
 * Removes a phone from the database
 * @route DELETE /api/phones/:id
 * @param req The Express request object containing the 'id' param
 * @param res - The Express response object
 * @returns A success message or a 404 error
 */
export const deletePhone = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const success = await phoneService.deletePhoneById(id);

    if (!success) {
      return res.status(404).json({ message: "Phone not found for deletion" });
    }

    res.status(200).json({ message: "Phone deleted successfully" });
  } catch (err) {
    console.error("Error deleting phone:", err);
    res.status(500).json({ message: "Server error deleting phone" });
  }
};
