import { Request, Response } from "express";
import * as phoneService from "../services/phoneService";

/**
 * Fetches a paginated list of phones. Supports parameters for page number and
 * limit per page. The response includes pagination metadata which indicates:
 *    - totalPages: The total number of pages available based on the total
 *      number of phones and the limit per page.
 *    - currentPage: The current page number being retrieved.
 *    - itemsPerPage: The number of phones returned per page (the limit).
 *    - hasNextPage: A boolean indicating if there is a next page available.
 *    - hasPrevPage: A boolean indicating if there is a previous page available.
 * @route GET /api/phones
 * @param req The Express request object which may contain 'page' and 'limit'
 * query parameters for pagination
 * @param res The Express response object
 * @returns A JSON response containing list of phones and pagination metadata
 */
export const getAllPhones = async (req: Request, res: Response) => {
  try {
    // Setting default values and limits for pagination
    const MAX_LIMIT = 50; // Limiting number of phones per page to prevent DDoS or memory issues
    const DEFAULT_LIMIT = 12; // Default limit if not specified of phones per page
    const PAGE_DEFAULT = 1; // Default page if not specified

    // Input sanitization for findAllPhones function
    const page = parseInt(req.query.page as string) || PAGE_DEFAULT;
    const limit = Math.min(parseInt(req.query.limit as string) || DEFAULT_LIMIT, MAX_LIMIT);
    const { phones, total } = await phoneService.findAllPhones(page, limit);

    // If no phones are found
    if (phones.length === 0 && total === 0) {
      return res.status(204).json({
        // 204 - No content found but successful request
        success: true,
        message: "No phones found",
        data: [],
        pagination: {
          totalPages: 0,
          currentPage: page,
          itemsPerPage: limit,
          hasNextPage: false,
          hasPrevPage: false,
        },
      });
    }

    // Returning a list of phones with pagination metadata
    res.status(200).json({
      success: true,
      message: "Phones retrieved successfully",
      data: phones,
      pagination: {
        totalPages: Math.ceil(total / limit), // calculates total # of pages
        currentPage: page,
        itemsPerPage: limit,
        hasNextPage: page * limit < total,
        hasPrevPage: page > 1,
      },
    });
  } catch (err) {
    console.error("Error fetching phones:", err);
    res.status(500).json({ message: "Server error fetching phones" });
  }
};

/**
 * Fetches a specific phone using its ID,
 * @route GET /api/phones/:id
 * @param req The Express request object containing the 'id' param
 * @param res The Express response object
 * @returns The phone data
 */
export const getPhoneById = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const phone = await phoneService.findPhoneById(id);
    if (!phone) {
      return res.status(404).json({ message: `Phone with ID '${id}' not found` });
    }
    res.status(200).json(phone);
  } catch (err) {
    console.error(`Error fetching phone ${req.params.id}:`, err);
    res.status(500).json({ message: "Server error" });
  }
};

/**
 * Creates a new phone. The 'id' field is auto-generated by the model if omitted.
 * @route POST /api/phones
 * @param req The Express request object containing phone data in the body
 * @param res The Express response object
 * @returns The created phone object
 */
export const createPhone = async (req: Request, res: Response) => {
  try {
    // Validation the schema just incase there are missing fields
    if (!req.body.name || !req.body.brand) {
      return res.status(400).json({ message: "Missing required fields: name, brand" });
    }

    const newPhone = await phoneService.createNewPhone(req.body);
    res.status(201).json(newPhone);
  } catch (err: any) {
    console.error("Error creating phone:", err);

    // Handling duplicate key error
    if (err.code === 11000) {
      return res.status(409).json({ message: "A phone with this ID already exists." });
    }
    res.status(500).json({ message: "Server error creating phone" });
  }
};

/**
 * Updates an existing phone's details.
 * @route PUT /api/phones/:id
 * @param req - The Express request object containing 'id' param and update data
 * @param res - The Express response object
 * @returns The updated phone object
 */
export const updatePhone = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const updatedPhone = await phoneService.updatePhoneById(id, req.body);

    if (!updatedPhone) {
      return res.status(404).json({ message: "Phone not found for update" });
    }

    res.status(200).json(updatedPhone);
  } catch (err) {
    console.error("Error updating phone:", err);
    res.status(500).json({ message: "Server error updating phone" });
  }
};

/**
 * Removes a phone from the database
 * @route DELETE /api/phones/:id
 * @param req The Express request object containing the 'id' param
 * @param res - The Express response object
 * @returns A success message or a 404 error
 */
export const deletePhone = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const success = await phoneService.deletePhoneById(id);

    if (!success) {
      return res.status(404).json({ message: "Phone not found for deletion" });
    }

    res.status(200).json({ message: "Phone deleted successfully" });
  } catch (err) {
    console.error("Error deleting phone:", err);
    res.status(500).json({ message: "Server error deleting phone" });
  }
};
